"""add_transformations_to_featureset

Revision ID: 71ce13b38a53
Revises: acbb434054fe
Create Date: 2026-01-13 08:40:15.755855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ce13b38a53'
down_revision: Union[str, None] = 'acbb434054fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE mlops_feature_sets ADD COLUMN IF NOT EXISTS transformations JSONB")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mlops_feature_sets', 'transformations')
    # ### end Alembic commands ###
