"""add_active_features_to_featureset

Revision ID: 75ca5dc6b3d9
Revises: 783e9f8e9fc2
Create Date: 2026-01-15 07:26:31.232013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ca5dc6b3d9'
down_revision: Union[str, None] = '783e9f8e9fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mlops_feature_sets', sa.Column('active_features', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mlops_feature_sets', 'active_features')
    # ### end Alembic commands ###
