"""Add InferenceDataset

Revision ID: 783e9f8e9fc2
Revises: 9cf2f5ff8bb9
Create Date: 2026-01-14 04:16:46.248265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783e9f8e9fc2'
down_revision: Union[str, None] = '9cf2f5ff8bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mlops_inference_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('feature_set_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['feature_set_id'], ['mlops_feature_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mlops_inference_datasets_id'), 'mlops_inference_datasets', ['id'], unique=False)
    op.create_index(op.f('ix_mlops_inference_datasets_name'), 'mlops_inference_datasets', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mlops_inference_datasets_name'), table_name='mlops_inference_datasets')
    op.drop_index(op.f('ix_mlops_inference_datasets_id'), table_name='mlops_inference_datasets')
    op.drop_table('mlops_inference_datasets')
    # ### end Alembic commands ###
