"""add_target_column_to_feature_set

Revision ID: 997bb660876d
Revises: 75ca5dc6b3d9
Create Date: 2026-01-15 07:48:12.996468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '997bb660876d'
down_revision: Union[str, None] = '75ca5dc6b3d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mlops_feature_sets', sa.Column('target_column', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mlops_feature_sets', 'target_column')
    # ### end Alembic commands ###
