"""add_target_and_params_to_model

Revision ID: 9cf2f5ff8bb9
Revises: 9f72c114ba86
Create Date: 2026-01-13 12:58:07.987581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf2f5ff8bb9'
down_revision: Union[str, None] = '9f72c114ba86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mlops_models', sa.Column('target_column', sa.String(), nullable=True))
    op.add_column('mlops_models', sa.Column('parameters', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mlops_models', 'parameters')
    op.drop_column('mlops_models', 'target_column')
    # ### end Alembic commands ###
