"""add_feature_names_to_model

Revision ID: 9f72c114ba86
Revises: e578d3e48358
Create Date: 2026-01-13 12:30:51.182740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f72c114ba86'
down_revision: Union[str, None] = 'e578d3e48358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mlops_models', sa.Column('feature_names', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mlops_models', 'feature_names')
    # ### end Alembic commands ###
