"""Fix table names

Revision ID: acbb434054fe
Revises: 
Create Date: 2026-01-13 04:59:17.902016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acbb434054fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mlops_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mlops_datasets_id'), 'mlops_datasets', ['id'], unique=False)
    op.create_index(op.f('ix_mlops_datasets_name'), 'mlops_datasets', ['name'], unique=True)
    op.create_table('mlops_feature_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('expression', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mlops_feature_definitions_id'), 'mlops_feature_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_mlops_feature_definitions_name'), 'mlops_feature_definitions', ['name'], unique=True)
    op.create_table('mlops_dataset_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('schema_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['mlops_datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mlops_dataset_versions_id'), 'mlops_dataset_versions', ['id'], unique=False)
    op.create_index(op.f('ix_mlops_dataset_versions_version'), 'mlops_dataset_versions', ['version'], unique=False)
    op.create_table('mlops_feature_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['mlops_dataset_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mlops_feature_sets_id'), 'mlops_feature_sets', ['id'], unique=False)
    op.create_table('mlops_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('feature_set_id', sa.Integer(), nullable=True),
    sa.Column('mlflow_run_id', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['feature_set_id'], ['mlops_feature_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mlops_models_id'), 'mlops_models', ['id'], unique=False)
    op.create_index(op.f('ix_mlops_models_mlflow_run_id'), 'mlops_models', ['mlflow_run_id'], unique=False)
    op.create_index(op.f('ix_mlops_models_name'), 'mlops_models', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mlops_models_name'), table_name='mlops_models')
    op.drop_index(op.f('ix_mlops_models_mlflow_run_id'), table_name='mlops_models')
    op.drop_index(op.f('ix_mlops_models_id'), table_name='mlops_models')
    op.drop_table('mlops_models')
    op.drop_index(op.f('ix_mlops_feature_sets_id'), table_name='mlops_feature_sets')
    op.drop_table('mlops_feature_sets')
    op.drop_index(op.f('ix_mlops_dataset_versions_version'), table_name='mlops_dataset_versions')
    op.drop_index(op.f('ix_mlops_dataset_versions_id'), table_name='mlops_dataset_versions')
    op.drop_table('mlops_dataset_versions')
    op.drop_index(op.f('ix_mlops_feature_definitions_name'), table_name='mlops_feature_definitions')
    op.drop_index(op.f('ix_mlops_feature_definitions_id'), table_name='mlops_feature_definitions')
    op.drop_table('mlops_feature_definitions')
    op.drop_index(op.f('ix_mlops_datasets_name'), table_name='mlops_datasets')
    op.drop_index(op.f('ix_mlops_datasets_id'), table_name='mlops_datasets')
    op.drop_table('mlops_datasets')
    # ### end Alembic commands ###
