"""Add name and desc to feature sets

Revision ID: e578d3e48358
Revises: 71ce13b38a53
Create Date: 2026-01-13 11:21:00.255769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e578d3e48358'
down_revision: Union[str, None] = '71ce13b38a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mlops_feature_sets', sa.Column('name', sa.String(), nullable=True))
    op.add_column('mlops_feature_sets', sa.Column('description', sa.String(), nullable=True))
    op.create_index(op.f('ix_mlops_feature_sets_name'), 'mlops_feature_sets', ['name'], unique=False)
    
    # Make existing columns nullable
    op.alter_column('mlops_feature_sets', 'dataset_version_id', existing_type=sa.Integer(), nullable=True)
    op.alter_column('mlops_feature_sets', 'version', existing_type=sa.String(), nullable=True)
    op.alter_column('mlops_feature_sets', 'path', existing_type=sa.String(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert nullable changes (Note: Data must exist if reverting to nullable=False, might fail if nulls introduced)
    # We assume for downgrade that we want to revert schema, but data might violate it if we created "empty" sets.
    # For safety in dev, we can try to set them back, but usually strictly required fields are hard to revert if data is messy.
    # We will just attempt to set them back.
    op.alter_column('mlops_feature_sets', 'path', existing_type=sa.String(), nullable=True) # Was True before? No, was False (implicitly). 
    # Actually models.py initially had them as nullable=False (default).
    # So to revert:
    op.alter_column('mlops_feature_sets', 'path', existing_type=sa.String(), nullable=True) # Keeping nullable True in downgrade for safety? No, strict revert means False.
    # However, postgres won't allow setting nullable=False if nulls exist.
    # We'll set them to True in downgrade as well to avoid breakage, or just drop the new columns.
    
    op.drop_index(op.f('ix_mlops_feature_sets_name'), table_name='mlops_feature_sets')
    op.drop_column('mlops_feature_sets', 'description')
    op.drop_column('mlops_feature_sets', 'name')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
